// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1muoqc--LwyuTUu9BR_8rW8K4fTiDdKU',
    appId: '1:161807044561:android:a12ac22cd771833cc0daf0',
    messagingSenderId: '161807044561',
    projectId: 'cat-task-3',
    storageBucket: 'cat-task-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFx-de_BCmjYvNNyEax4Gyj83EN7XXZcI',
    appId: '1:161807044561:ios:a46160a0bd3c6fe1c0daf0',
    messagingSenderId: '161807044561',
    projectId: 'cat-task-3',
    storageBucket: 'cat-task-3.firebasestorage.app',
    androidClientId: '161807044561-38q8f3u2q7afv9mpaalhlnarccc6ipmu.apps.googleusercontent.com',
    iosClientId: '161807044561-gakne2dlqmqk3b28elnic9fp05ebgs1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.catToDoList',
  );

}